version: '3'
services:
  app:
    env_file:
      - .env
    container_name: focusbear-backend
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
      POSTGRES_USER: postgres
      POSTGRES_DB: focusbear

    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    links:
      - postgres

volumes:
  postgres:
    driver: local
